### ISSUE TITLE
Sample Perlin code only produces 0

### ISSUE THREAD

**Issue by willfleetw** [Razaekel/noise-rs#269]
When I use this package and follow the sample code

`
use noise::{NoiseFn, Perlin};

fn main() {
    let perlin = Perlin::new();
    let val = perlin.get([42.0, 37.0, 2.0]);

    assert_eq!(val, 0.0);
}
`

It ALWAYS returns 0, regardless of what input I give.

**Comment by IoIxD** [comment]
I have no idea why they chose to close this because there's nothing on the docs on this and aside from understanding how perlin noise works, there is no indication as to why this would be a thing. In fact, I don't even understand how perlin works, so I'm probably misunderstanding, but I do suddenly remember having to do this in my last project using perlin noise. But alas...

You need to put a non-zero decimal next to your number. `1.1` instead of `1.0`, or even `1.000001`. 

I'm sure this isn't actually the case but until somebody corrects me, then it may as well be the answer.

**Comment by frnsys** [comment]
I just ran into this too. I'm iterating over the pixels of an image so I have x and y coordinates that are whole numbers. If I pass these directly into the perlin function, e.g. ` let val = perlin.get([x as f64, y as f64]);`, the value is always 0. If I add e.g. 0.1 to each then I get different values.

**Comment by amaranth** [comment]
This should perhaps be added to the documentation but this is by design, Perlin noise is supposed to return 0 on whole numbers. I'd suggest dividing your coordinates by the image length/height so you have a 0-1 range to feed in to perlin.

**Comment by willfleetw** [comment]
Yes, after digging through math behind perlin I found this was generally
expected, but the official documentation should be made to reflect this.
Copying any given random seed and perlin call code from the official
documentation should result in the same values universally.

Thanks,

William Fleetwood
